### ISSUE TITLE
dstStageMask includes VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT when the device does not have geometryShader feature enabled

### ISSUE THREAD

**Issue by mortie** [Ckef/groufix#14]
Running with MoltenVK, the tests output:

> 2.29e+02ms ERROR thread-0: groufix/core/vulkan.c:58: Vulkan: Validation Error: [ VUID-vkCmdPipelineBarrier-dstStageMask-04090 ] Object 0: handle = 0x6000013c02b8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4378cb6d | vkCmdPipelineBarrier(): .dstStageMask includes VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT when the device does not have geometryShader feature enabled. The Vulkan spec states: If the geometry shaders feature is not enabled, pname:dstStageMask must not contain VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT (https://vulkan.lunarg.com/doc/view/1.3.211.0/mac/1.3-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-dstStageMask-04090)

**Comment by Ckef** [comment]
Should be fixed by https://github.com/Ckef/groufix/commit/50d8ad48401d764e757fb70f951f8cd6ebd341e9
